apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pets
spec:
  type: state.azure.cosmosdb
  version: v1
  metadata:
  - name: url
    value: https://petspotr.documents.azure.com:443/
  - name: masterKey
    secretKeyRef:
      name: cosmos
      key: masterKey
  - name: database
    value: petspotr
  - name: collection
    value: pets
  - name: keyPrefix
    value: name
