version: '3'

services:
  app:
    image: mcr.microsoft.com/devcontainers/dotnet:0-7.0

    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock
      - ..:/workspace:cached

    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity

    network_mode: service:redis
  #redis:
  #  image: redis:latest
  #  volumes:
  #    # Forwards the local Docker socket to the container.
  #    - /var/run/docker.sock:/var/run/docker-host.sock
  #  ports:
  #    - "6379"