name: Deploy Application

on:
  push:
    branches:
      - main
    paths:
      - 'iac/kubernetes/**'
      - '.github/workflows/application.yaml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy Infrastructure
        run: |
          az deployment group create \
            --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --template-file iac/app.bicep \
            --parameters registryName=petspotr clusterName=petspotr serviceBusAuthRuleName=petspotr/authorizationrules/KEDA
