name: Build and Publish Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/containers.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/containers.yaml'

env:
  REGISTRY_ADDRESS: petspotr.azurecr.io

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Build and Push Backend
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ env.REGISTRY_ADDRESS }}/backend:latest
          file: src/backend/Dockerfile
          context: src/backend
      - name: Build and Push Frontend
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ env.REGISTRY_ADDRESS }}/frontend:latest
          file: src/frontend/Dockerfile
          context: src/frontend
