name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run Playwright tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: |
        cd tests/playwright
        npm ci
    - name: Install Playwright Browsers
      run:
        cd tests/playwright
        pwd
        npx playwright install --with-deps
    - name: Run Playwright tests
      run:
        cd tests/playwright
        npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: tests/playwright/playwright-report/
        retention-days: 30
